import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

const dmSans = DM_Sans({
	variable: '--font-dm-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${dmSans.variable} antialiased bg-[url('/images/bg-light-theme.png')] dark:bg-[url('/images/bg-dark-theme.png')] text-neutral-900 dark:text-neutral-100 bg-cover font-sans`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
